name: Build and Deploy Bot container to AWS EC2

on:
  push:
    branches: [ main ]
  path:
    - 'scripts/**'
    - 'utils/**'
    - 'database_service.py'
    - 'Dockerfile'
    - 'main.py'
    - 'requirements.txt'
    - '.github/workflows/bot-deploy.yml'

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/aurelius:latest

  deploy_bot:
    runs-on: ubuntu-latest
    needs: build_image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Send only necessary files
        run: |
          scp -i ~/.ssh/key.pem -r ./scripts ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Aurelius/
          
      - name: Deploy Bot on EC2
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd Aurelius
            docker stop aurelius
            docker rm aurelius
            docker rmi -f aurelius || true
            docker pull ${{ secrets.DOCKER_NAME }}/aurelius:latest
            docker tag ${{ secrets.DOCKER_NAME }}/aurelius:latest aurelius
            ./scripts/run_bot_container.sh
            docker rmi -f ${{ secrets.DOCKER_NAME }}/aurelius:latest
          EOF