name: Deploy to EC2 (Docker)

on:
  push:
    branches: [ main ]

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/aurelius:latest
          
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: aurelius-webpage/package-lock.json

      - name: Install deps and build website
        working-directory: aurelius-webpage
        run: |
          npm ci
          npm run build
      
      - name: Archive web production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: aurelius-webpage/dist
          if-no-files-found: error

  deploy_bot:
    runs-on: ubuntu-latest
    needs: build_image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Send only necessary files
        run: |
          scp -i ~/.ssh/key.pem -r ./scripts ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Aurelius/
          
      - name: Deploy Bot on EC2
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd Aurelius
            docker stop aurelius
            docker rm aurelius
            docker rmi -f aurelius || true
            docker pull ${{ secrets.DOCKER_NAME }}/aurelius:latest
            docker tag ${{ secrets.DOCKER_NAME }}/aurelius:latest aurelius
            ./scripts/run_bot_container.sh
            docker rmi -f ${{ secrets.DOCKER_NAME }}/aurelius:latest
          EOF

  deploy_website:
    runs-on: ubuntu-latest
    needs: build_website
    steps:
      - name: Download web production artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3 

      - name: Upload website files to S3 with cache headers
        run: |
          # Cache-bust strategy:
          # - HTML: no-cache so clients revalidate and pick up new asset URLs
          # - Static assets (hashed by Vite): long-lived, immutable cache
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --cache-control "no-cache, no-store, must-revalidate" \
            --exclude "*" --include "*.html"

          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude "*.html"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html" "/"