name: Deploy to EC2 (Docker)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/aurelius:latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: aurelius-webpage/package-lock.json

      - name: Install deps and build website
        working-directory: aurelius-webpage
        run: |
          npm ci
          npm run build
      
      - name: Archive web production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: aurelius-webpage/dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Send only necessary files
        run: |
          scp -i ~/.ssh/key.pem -r ./scripts ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Aurelius/
      #     scp -i ~/.ssh/key.pem -r ./utils ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Aurelius/
      #     scp -i ~/.ssh/key.pem ./main.py ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Aurelius/
      #     scp -i ~/.ssh/key.pem ./database_service.py ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Aurelius/
      #     scp -i ~/.ssh/key.pem ./Dockerfile ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Aurelius/
      #     scp -i ~/.ssh/key.pem ./requirements.txt ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Aurelius/
          
      - name: Deploy Bot on EC2
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd Aurelius
            docker stop aurelius
            docker rm aurelius
            docker rmi -f aurelius || true
            docker pull ${{ secrets.DOCKER_NAME }}/aurelius:latest
            docker tag ${{ secrets.DOCKER_NAME }}/aurelius:latest aurelius
            ./scripts/run_bot_container.sh
            docker rmi -f ${{ secrets.DOCKER_NAME }}/aurelius:latest
          EOF

      - name: Download web production artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3 

      - name: Upload website files to S3
        run: |
          ls -l
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete